### ISSUE TITLE
Plugin not working if linked under $HOME

### ISSUE THREAD

**Issue by pihentagy** [rolfkleef/zim-plantuml#1]
Using zim 0.65
If I put to  ~/.local/lib/pymodules/python2.7/site-packages/zim/plugins it dumps the trace below.
If I hack the py file to global directory /usr/lib/pymodules/python2.7/zim/plugins it works.

```
ERROR: Could not load plugin plantumleditor
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/zim/gui/preferencesdialog.py", line 307, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/usr/lib/pymodules/python2.7/zim/plugins/__init__.py", line 208, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/pymodules/python2.7/zim/utils.py", line 33, in get_module
    mod = __import__(name)
ImportError: No module named plantumleditor

```

**Comment by rolfkleef** [comment]
Thanks for the report! It might be that the path changed in a newer version of Ubuntu or Zim:

I'm on 16.04LTS by now, and it seems the plugin currently lives in my folder ~/.local/share/zim/plugins/ by now. Zim 0.65 as well.

I'll update the guidance!
